navigation-bar
sirtobiwan/Solar-Calculator-Capstone-Project pull request #33
Opened 2023-05-18 12:35 UTC by sirtobiwan

2023-05-19 08:28 UTC, NikRoe requested changes
Hi Tobias,

your app looks really good already! I left only two comments for you to take a look at.

Really great that you reuse some of your styled components.

In case of your Layout component, you could have a reusable component that you don't need to call in every page manually, if you follow this [example from Next.js](https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts).

I recommend taking a look at the link and try to implement the Layout component. This will make your code even cleaner!

Keep it up 🙌

2023-05-19 08:28 UTC, NikRoe commented on components/Layout/index.js
> +    </>
You don't need fragments here:

```suggestion
    <StyledHeader>
      <h1>My Solar Calculator</h1>
    </StyledHeader>
```

2023-05-19 08:28 UTC, NikRoe commented on components/NavigationBar/index.js
> +const NavItem = styled.div`
a paragraph would be more semantic here:

```suggestion
const NavItem = styled.p`
```

2023-05-22 09:54 UTC, sirtobiwan commented
Hi Niklas,

thanks for the feedback.

In this case I need to call the layout component on every page.

Everything else was updated

2023-05-22 09:54 UTC, merged

2023-05-22 09:59 UTC, NikRoe commented
You would only need to call it in your `_app.js` and not on every page.

2023-05-22 10:11 UTC, sirtobiwan commented
Exactly, but then it would be displayed on every page but I don't wanna have it displayed on my landingpage (index.js)

2023-05-22 10:32 UTC, NikRoe commented
Ah, I see. Then I misunderstood what you intended to do.